Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path('rent/', include('rent.urls' , namespace='rent'))
               ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
app_name = 'rent'
urlpatterns = [
    path('' , views.RentUsersView.as_view() , name='rent_users'),
    path('admin-rent' , views.RentRoomAdmin.as_view() , name='admin_rent'),
    path('admin-rent-details/<int:pk>' , views.AdminRentRoomDetails.as_view() , name='admin_rent_details'),
    path('rent-details/<int:pk>' , views.RentRoomDetails.as_view() , name='rent_details'),
    path('all-rent/<int:pk>' , views.AllRentUser.as_view() , name='all_rent')
]
 

users/urls.py
from idlelib.textview import view_file

from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('admin_page' , views.AdminPage.as_view(), name='admin_page'),
    path('user_page' , views.user_page, name='user_page'),
    path('logout' , views.LogoutUser.as_view() , name='logout_user'),
    path('register/' , views.RegisterUserPage.as_view(), name='register'),
    path('datails/<int:id>' , views.admin_details , name='admin_details')
]

users/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomeUser(AbstractUser):
    STATUS = (
        ('admin' , 'admin') ,
        ('owner' , 'owner'),
        ('customer' , 'customer')
    )
    phone = models.CharField(max_length=13,unique=True)
    room_id = models.CharField(max_length=5 , unique=True , blank=True , null=True)
    room_size = models.PositiveIntegerField(blank=True , null=True)
    status = models.CharField(choices=STATUS , blank=True , null= True , max_length=18)

    def __str__(self):
        if self.room_id is not None:
            return self.room_id
        else:
            return self.username

users/forms.py
from django import forms
from rent.models import CustomeUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomeUser
        fields = UserCreationForm.Meta.fields + ('phone', 'room_id')


class CustomeUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomeUser
        fields = UserChangeForm.Meta.fields


class LoginForm(forms.Form):
    user = forms.CharField(max_length=100)
    password = forms.CharField(max_length=100)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=50)
    f_name = forms.CharField(max_length=50)
    l_name = forms.CharField(max_length=50)
    phone = forms.CharField(max_length=15)
    room_id = forms.CharField(max_length=5)
    room_size = forms.IntegerField()
    password = forms.CharField(max_length=50)

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if CustomeUser.objects.filter(phone=phone).exists():
            raise forms.ValidationError('تلفن وارد شده تکراری است')
        return phone

users/views.py
from django.contrib.auth.password_validation import password_changed
from django.shortcuts import render, redirect
from django.template.context_processors import request
from django.views import generic
from django.urls import reverse_lazy
from django.contrib.auth.views import LogoutView
from .forms import *
from django.contrib.auth import authenticate, login, logout
from .models import CustomeUser
from django.contrib.auth.mixins import LoginRequiredMixin
from rent.models import RentRoom
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required


# Create your views here.

# def home(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             data = form.cleaned_data
#             try:
#                 user = authenticate(request, username=CustomeUser.objects.get(phone=data['user']),
#                                     password=data['password'])
#             except:
#
#                 user = authenticate(request, username=data['user'], password=data['password'])
#
#             if user is not None:
#                 login(request, user)
#                 if user.is_staff:
#                     return redirect('users:admin_page')
#                 else:
#                     return redirect('users:user_page')
#
#     else:
#         form = LoginForm()
#
#     return render(request, 'users/login.html', {'form': form})
#

class HomePageView(generic.FormView):
    template_name = 'users/login.html'
    form_class = LoginForm

    def form_valid(self, form):
        data = form.cleaned_data
        try:
            user = authenticate(request, username=CustomeUser.objects.get(phone=data['user']),
                                password=data['password'])
        except:
            user = authenticate(request, username=data['user'], password=data['password'])
        if user is not None:
            login(self.request, user)
            if user.is_staff:
                return redirect('users:admin_page')
            else:
                return redirect('users:user_page')
        else:
            return self.form_invalid(form)


# def admin_page(request):
#     users = CustomeUser.objects.filter(status='owner')
#     return render(request, 'users/admin.html', {'users': users})

class AdminPage(LoginRequiredMixin, generic.ListView):
    model = CustomeUser
    template_name = 'users/admin.html'
    context_object_name = 'users'

    def get_queryset(self):
        return CustomeUser.objects.filter(status='owner')


@login_required(login_url='users:home')
def user_page(request):
    return render(request, 'users/users.html')


# def register_user(request):
#     if request.method == 'POST':
#         form = RegisterForm(request.POST)
#         if form.is_valid():
#             data = form.cleaned_data
#             user = CustomeUser.objects.create(username=data['username'], first_name=data['f_name'],
#                                               last_name=data['l_name'], phone=data['phone']
#                                               , room_id=data['room_id'], room_size=data['room_size'],
#                                               password=['password'], status='owner')
#             user.save()
#             return redirect('users:register')
#     else:
#         form = RegisterForm()
#
#     return render(request, 'users/register.html', {'form': form})


class RegisterUserPage(LoginRequiredMixin, generic.FormView):
    form_class = RegisterForm
    template_name = 'users/register.html'

    def form_valid(self, form):
        data = form.cleaned_data
        user = CustomeUser.objects.create(username=data['username'], first_name=data['f_name'],
                                          last_name=data['l_name'], phone=data['phone']
                                          , room_id=data['room_id'], room_size=data['room_size'],
                                          status='owner')
        user.set_password(data['password'])
        user.save()
        return redirect('users:register')


# def logout_user(request):
#     logout(request)
#     return redirect('users:home')


class LogoutUser(LogoutView):
    next_page = 'users:home'


# class AdminDetailsView(generic.DetailView , LoginRequiredMixin):
#     model = RentRoom
#     template_name = 'users/admin-details.html'
#     context_object_name = 'bills'
#

@login_required(login_url='users:home')
def admin_details(request, id):
    user = CustomeUser.objects.get(id=id)
    bills = RentRoom.objects.filter(user_id=id)
    paginator = Paginator(bills, 10)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {'user_derail': user}
    return render(request, 'users/admin-details.html', context)

users/templates/users/admin-details.html
{% extends '_base-admin.html' %}
{% load static %}
{% block body %}
<div class="p-5"
     style="background-image: url('../static/img/Login_bg.jpg'); background-size: cover; height: 90.3vh ; width: 100%">
    <div class="container">
        <div class="card bg-dark text-light ">
            <div class="card-body p-5">
                <div class="row gy-4 gx-0">
                    <div class="col-md-3"></div>
                    <div class=" col-md-6 text-center">
                        <div class=" mx-2 py-2 border rounded">
                            نام کاربری : {{ user_derail.username }}
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                    <div class=" col-md-6 text-center">
                        <div class=" mx-2 py-2 border rounded">
                            نام : {{ user_derail.first_name }}
                        </div>
                    </div>
                    <div class=" col-md-6 text-center">
                        <div class=" mx-2 py-2 border rounded">
                            نام خانوادگی : {{ user_derail.last_name }}
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                    <div class=" col-md-6 text-center">
                        <div class=" mx-2 py-2 border rounded">
                            تلفن : {{ user_derail.phone }}

                        </div>
                    </div>
                    <div class="col-md-3"></div>
                    <div class=" col-md-6 text-center">
                        <div class=" mx-2 py-2 border rounded">
                             شناسه ملک : {{ user_derail.room_id }}
                        </div>
                    </div>
                    <div class=" col-md-6 text-center">
                        <div class=" mx-2 py-2 border rounded">
                             متراژ ملک : {{ user_derail.room_size }}
                        </div>
                    </div>
                    <div class="col-md-3"></div>
                    <div class=" col-md-6 text-center">
                        <div class=" mx-2 p-2 border rounded">
                            {% if user_derail.status == None %}
                            <span class="badge py-2 px-3 text-bg-warning">سوپر ادمین</span>

                            {% elif user_derail.status == "admin" %}
                            <span class="badge py-2 px-3 text-bg-primary">ادمین</span>

                            {% elif user_derail.status == "owner" %}
                            <span class="badge py-2 px-3 text-bg-success">مالک</span>

                            {% endif %}
                        </div>
                        <div class="col-md-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

users/templates/users/admin.html
{% extends '_base-admin.html' %}
{% block body %}
<div class="m-5">
    <table class="table table-dark table-striped text-center ">
        <thead class="table-light ">
        <tr>
            <th>نام کاربری</th>
            <th>نام</th>
            <th>نام خانوادگی</th>
            <th>تلفن</th>
            <th>شناسه ملک</th>
            <th>متراژ ملک</th>
            <th>وضعیت</th>
            <th>جزئیات</th>
            <th>قبوض کاربر</th>
        </tr>
        </thead>

        <tbody class="table-group-divider">
        {% for user in users %}
        <tr>
            <td>{{ user.username }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>{{ user.phone }}</td>
            <td>{{ user.room_id }}</td>
            <td>{{ user.room_size }}</td>


            {% if user.status == None %}
            <td>
                <span class="badge text-bg-warning">سوپر ادمین</span>
            </td>
            {% elif user.status == "admin" %}
            <td>
                <span class="badge text-bg-primary">ادمین</span>
            </td>
            {% elif user.status == "owner" %}
            <td>
                <span class="badge text-bg-success">مالک</span>
            </td>
            {% endif %}
            <td><a class="btn btn-outline-light btn-sm" href=" {% url 'users:admin_details' user.id %} ">مشاهده </a></td>
            <td><a class="btn btn-outline-light btn-sm" href="{% url 'rent:all_rent' user.id %}"> مشاهده</a></td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

users/templates/users/login.html
{% extends '_base.html' %}
{% block body %}
        <div id="layoutAuthentication">
            <div id="layoutAuthentication_content">
                <main>
                    <div class="container">
                        <div class="row justify-content-center mt-5">
                            <div class="col-lg-5">
                                <div class="card bg-dark shadow-lg border-0 rounded-lg mt-5">
                                    <div class="card-header"><h3 class="text-center text-light font-weight-light my-4">ورود</h3></div>
                                    <div class="card-body">
                                        <form method="post">
                                            {% csrf_token %}
                                            <div class="form-floating mb-3">
                                                <input class="form-control" name="user" id="inputEmail" type="text" placeholder="نام کاربری" />
                                                <label for="inputEmail">نام کاربری</label>
                                            </div>
                                            <div class="form-floating mb-3">
                                                <input class="form-control" name="password" id="inputPassword" type="password" placeholder="رمز عبور" />
                                                <label for="inputPassword">رمز عبور</label>
                                            </div>
                                             <div class="d-flex align-items-center justify-content-center mt-4 mb-0">
                                                <button type="submit" class="btn btn-primary pt-1 pb-2 px-4">ورود</button>
                                            </div>
                                        </form>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </main>
            </div>
         </div>

{% endblock %}

users/templates/users/register.html
{% extends '_base-admin.html' %}
{% block body %}
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="col-lg-7">
                        <div class="card bg-dark shadow-lg border-0 rounded-lg mt-3">
                            <div class="card-header"><h3 class="text-center text-light font-weight-light my-4">ساخت
                                کاربر</h3></div>
                            <div class="card-body">
                                <form method="post">
                                    {% csrf_token %}

                                        <div class="form-floating mb-3">
                                            <input name="username" class="form-control " id="inputEmail" type="text"
                                                   placeholder=""/>
                                            <label for="inputEmail"> نام کاربری </label>
                                        </div>
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <div class="form-floating mb-3 mb-md-0">
                                                <input name="f_name" class="form-control" id="inputFirstName"
                                                       type="text"
                                                       placeholder=""/>
                                                <label for="inputFirstName">نام</label>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-floating">
                                                <input name="l_name" class="form-control" id="inputLastName" type="text"
                                                       placeholder=" "/>
                                                <label for="inputLastName">نام خانوادگی</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input name="phone" class="form-control" id="inputEmail" type="tel"
                                               placeholder=""/>
                                        <label for="inputEmail">تلفن</label>
                                    </div>
                                    <div class="row mb-3">
                                        <div class="col-md-6">
                                            <div class="form-floating mb-3 mb-md-0">
                                                <input name="room_id" class="form-control" id="inputPassword"
                                                       type="text"
                                                       placeholder=""/>
                                                <label for="inputPassword">شناسه ملک</label>
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="form-floating mb-3 mb-md-0">
                                                <input name="room_size" class="form-control" id="inputPasswordConfirm"
                                                       type="text"
                                                       placeholder=""/>
                                                <label for="inputPasswordConfirm">متراژ ملک</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="form-floating mb-3">
                                        <input name="password" class="form-control" id="inputEmail" type="tel"
                                               placeholder=""/>
                                        <label for="inputEmail">رمز عبور</label>
                                    </div>
                                    <div class="mt-4 mb-0">
                                        <div class="d-grid">
                                            <button type="submit" class="btn btn-primary btn-block pt-0 btn-lg">
                                                ساخت کاربر
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>

{% endblock %}

users/templates/users/users.html
{% extends '_base.html' %}
{% block body %}
<h1>خوش آمدید</h1>
{% endblock %}