Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path('rent/', include('rent.urls' , namespace='rent'))
               ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
app_name = 'rent'
urlpatterns = [
    path('' , views.RentUsersView.as_view() , name='rent_users'),
    path('admin-rent' , views.RentRoomAdmin.as_view() , name='admin_rent'),
    path('admin-rent-details/<int:pk>' , views.AdminRentRoomDetails.as_view() , name='admin_rent_details'),
    path('rent-details/<int:pk>' , views.RentRoomDetails.as_view() , name='rent_details'),
    path('all-rent/<int:pk>' , views.AllRentUser.as_view() , name='all_rent')
]
 

rent/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.utils import timezone
from django_jalali.db import models as jmodels
from users.models import CustomeUser
from django.db.models.signals import post_save, post_delete

import jdatetime


# Create your models here.

class RentRoom(models.Model):
    user = models.ForeignKey(CustomeUser, limit_choices_to={'status': 'owner'}, on_delete=models.CASCADE,
                             related_name='user_rent')
    price = models.PositiveIntegerField()
    start_date = jmodels.jDateField()
    end_date = jmodels.jDateField()
    best_date = jmodels.jDateField()
    detail = models.TextField(blank=True, null=True)
    golden_date = jmodels.jDateField(blank=True)
    discount = models.PositiveSmallIntegerField(blank=True, null=True)
    is_active = models.BooleanField(default=True)
    total_price = models.PositiveIntegerField(blank=True, null=True)
    paid = models.BooleanField(default=False)
    create = jmodels.jDateTimeField(auto_now_add=True)
    update = jmodels.jDateTimeField(auto_now=True)

    def __str__(self):
        return self.user.room_id

    @property
    def total_price(self):
        time = timezone.now().date()

        if self.discount:
            if self.start_date <= time <= self.golden_date:
                total = int(self.price * self.user.room_size)
                offer = (total * self.discount) / 100
                return int(total - offer)
            elif time > self.golden_date:
                total = self.price * self.user.room_size
                return int(total)


        elif not self.discount:
            total = self.price * self.user.room_size
            return int(total)

    def is_active(self):
        time = timezone.now().date()
        if time > self.end_date:
            self.is_active = False
            return self.is_active
        return self.is_active


class RentHistory(models.Model):
    user = models.ForeignKey(CustomeUser, on_delete=models.CASCADE, related_name='user_history')
    price = models.PositiveIntegerField(blank=True)
    paid = models.BooleanField(default=False)
    total_price = models.PositiveBigIntegerField(blank=True, null=True)
    created = jmodels.jDateTimeField(auto_now_add=True)
    paid_change = jmodels.jDateTimeField(auto_now=True)

    def __str__(self):
        return self.user.room_id


def rent_history_save(sender, instance, created, *args, **kwargs):
    data = instance
    if created:
        RentHistory.objects.create(user=data.user, price=data.price, created=data.create, paid_change=data.update,
                                   total_price=data.total_price)


post_save.connect(rent_history_save, sender=RentRoom)


@receiver(post_delete, sender=RentRoom)
def rent_history_delete(sender, instance, *args, **kwargs):
    RentHistory.objects.filter(user=instance.user).delete()

rent/forms.py
from django import forms
from .models import *
from django_jalali.forms import jDateField, jDateInput
from django_jalali.admin.widgets import AdminjDateWidget
from jalali_date.fields import JalaliDateField
from jalali_date.widgets import AdminJalaliDateWidget
from django_jalali.forms import jDateField
from .widgets import JalaliDateWidget
#

class RentRoomForm(forms.ModelForm):
    start_date = forms.CharField(widget=JalaliDateWidget())
    end_date = forms.CharField(widget=JalaliDateWidget())
    best_date = forms.CharField(widget=JalaliDateWidget())
    golden_date = forms.CharField(required=False, widget=JalaliDateWidget())

    class Meta:
        model = RentRoom
        fields = ['user', 'start_date', 'end_date', 'best_date', 'golden_date', 'price', 'discount', 'detail']

    def clean_start_date(self):
        return self.convert_jalali_to_gregorian('start_date')

    def clean_end_date(self):
        return self.convert_jalali_to_gregorian('end_date')

    def clean_best_date(self):
        return self.convert_jalali_to_gregorian('best_date')

    def clean_golden_date(self):
        golden_date = self.cleaned_data.get('golden_date')
        if golden_date:
            return self.convert_jalali_to_gregorian('golden_date')
        return None

    def convert_jalali_to_gregorian(self, field_name):
        jalali_date = self.cleaned_data.get(field_name)
        try:
            year, month, day = map(int, jalali_date.split('/'))
            gregorian_date = jdatetime.date(year, month, day).togregorian()
            return gregorian_date
        except Exception:
            raise forms.ValidationError("تاریخ وارد شده نامعتبر است.")

rent/views.py
from django.http import HttpResponseForbidden
from django.shortcuts import render
from .models import *
from django.utils import timezone
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import RentRoomForm
from django.urls import reverse_lazy
from jdatetime import date, datetime
import jdatetime
from django.contrib.auth.mixins import UserPassesTestMixin


def jalali_to_gregorian(jalali_date):
    jalali_datetime = datetime.strptime(jalali_date, "%Y/%m/%d").date()
    gregorian_datetime = jalali_datetime.togregorian()
    return gregorian_datetime


# Create your views here.
# def rent_users(request):
#     bill = RentRoom.objects.filter(user_id=request.user.id)
#     context = {'bill': bill}
#     return render(request, 'rent/userRent.html', context)
#

class RentUsersView(LoginRequiredMixin, generic.ListView):
    model = RentRoom
    template_name = 'rent/userRent.html'
    context_object_name = 'bill'

    def get_queryset(self):
        return RentRoom.objects.filter(user_id=self.request.user.id)


class RentRoomAdmin(LoginRequiredMixin, UserPassesTestMixin, generic.CreateView):
    form_class = RentRoomForm
    template_name = 'rent/admin-rent.html'
    context_object_name = 'form'
    success_url = reverse_lazy('users:admin_page')

    def test_func(self):
        user = self.request.user
        return user.is_authenticated and (user.status == 'admin' or user.is_superuser)

    def handle_no_permission(self):
        return HttpResponseForbidden("شما اجازه دسترسی به این صفحه را ندارید.")

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        # در اینجا نیازی به تبدیل تاریخ نیست زیرا در فرم انجام شده است
        # اگر نیاز به پردازش اضافی دارید، می‌توانید آن را اینجا اضافه کنید
        return super().form_valid(form)


# def creat_rent(request):
#     if request.method == "POST":
#         form = RentRoomForm(request.POST)
#         if form.is_valid() :
#             data = form.cleaned_data
#             RentRoom.objects.create(user_id=data['user'] , price=data['price'] , start_date=data['start_date'] , discount=data['discount'],
#                                     end_date=data['end_date'] , best_date=data['best_date'] , golden_date=data['golden_date'])
#
#
#     else:
#         form =RentRoomForm()
#     return render(request , 'rent/admin-rent.html')

class AdminRentRoomDetails(UserPassesTestMixin, LoginRequiredMixin, generic.DetailView):
    model = RentRoom
    template_name = 'rent/admin-rent-details.html'
    context_object_name = 'bill'

    def test_func(self):
        user = self.request.user

        return user.is_authenticated and (user.status == 'admin' or user.is_superuser or user.id == self.kwargs['pk'])

    def handle_no_permission(self):
        return HttpResponseForbidden("شما اجازه دسترسی به این صفحه را ندارید.")


class RentRoomDetails(LoginRequiredMixin, generic.DetailView):
    model = RentRoom
    template_name = 'rent/rent-details.html'
    context_object_name = 'bill'


class AllRentUser(UserPassesTestMixin, generic.ListView):
    model = RentRoom
    template_name = 'rent/all-rent.html'
    context_object_name = 'bill'

    def get_queryset(self):
        rents = RentRoom.objects.filter(user_id=self.kwargs['pk'])
        return rents

    def test_func(self):
        user = self.request.user

        return user.is_authenticated and (user.status == 'admin' or user.is_superuser or user.id == self.kwargs['pk'])

    def handle_no_permission(self):
        return HttpResponseForbidden("شما اجازه دسترسی به این صفحه را ندارید.")

rent/templates/rent/admin-rent-details.html
{% extends '_base-admin.html' %}
{% load static %}
{% block body %}
    <div class="p-5">
        <div class="container">
            <div class="card bg-dark text-light ">
                <div class="card-body p-5">
                    <div class="row gy-4 gx-0">
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                تاریخ شروع قبض : {{ bill.start_date }}

                            </div>
                        </div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                تاریخ پایان قبض : {{ bill.end_date }}
                            </div>
                        </div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                قیمت : {{ bill.price }} ریال
                            </div>
                        </div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                تخفیف : %{{ bill.discount }}
                            </div>
                        </div>
                        <div class="col-md-3"></div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                پرداختی : {{ bill.total_price }} ریال
                            </div>
                        </div>
                        <div class="col-md-3"></div>
                        <div class="col-md-3"></div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 p-2 border rounded">
                                {% if bill.paid == False %}

                                    <span class="badge py-2  px-3 text-bg-danger">پرداخت نشده</span>
                                  
 
                                {% elif bill.paid == True %}
                                    <span class="badge py-2 px-3 text-bg-success">پرداخت شده</span>

                                {% endif %}
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

rent/templates/rent/admin-rent.html
{% extends "_base-admin.html" %}
{% load jformat %}

{% block body %}
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    <div class="row justify-content-center">
                        <div class="col-lg-7">
                            <div class="card bg-dark shadow-lg border-0 rounded-lg mt-3">
                                <div class="card-header">
                                    <h3 class="text-center text-light font-weight-light my-4">ساخت قبض</h3>
                                </div>
                                <div class="card-body">
                                    <form method="post">
                                        {% csrf_token %}

                                        <!-- فیلد کاربر -->

                                        <div class="row mb-3">
                                            <div class="col-4  d-flex align-items-center justify-content-end"><label
                                                    for="user" class="text-light">کاربر :</label>
                                            </div>
                                            <div class="form col-4">

                                                <select class="form-select" id="user" name="user">
                                                    {% for choice in form.user.field.choices %}
                                                        <option value="{{ choice.0 }}"
                                                                {% if form.user.value == choice.0 %}selected{% endif %}>
                                                            {{ choice.1 }}
                                                        </option>
                                                    {% endfor %}
                                                </select>
                                                {% if form.user.errors %}
                                                    <div class="text-danger">{{ form.user.errors }}</div>
                                                {% endif %}

                                            </div>
                                            <div class="col-4"></div>
                                        </div>


                                        <!-- فیلدهای تاریخ با ویژگی data-jdp -->
                                        <div class="row mb-3">
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input type="text" class="form-control" name="start_date"
                                                           id="start_date"
                                                           placeholder=""
                                                           data-jdp>
                                                    <label for="start_date">تاریخ
                                                        شروع</label>

                                                    {% if form.start_date.errors %}
                                                        <div class="text-danger">{{ form.start_date.errors }}</div>
                                                    {% endif %}
                                                </div>
                                            </div>

                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input type="text" class="form-control" name="end_date"
                                                           id="end_date"
                                                           placeholder=""
                                                           data-jdp>
                                                    <label for="end_date">تاریخ
                                                        پایان</label>
                                                    {% if form.end_date.errors %}
                                                        <div class="text-danger">{{ form.end_date.errors }}</div>
                                                    {% endif %}
                                                </div>

                                            </div>

                                        </div>
                                        <div class="row mb-3">
                                            <div class="col-md-12">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input type="text" class="form-control" name="best_date"
                                                           id="best_date"
                                                           placeholder=""
                                                           data-jdp>
                                                    <label for="best_date">بهترین
                                                        تاریخ</label>
                                                    {% if form.best_date.errors %}
                                                        <div class="text-danger">{{ form.best_date.errors }}</div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mb-3">
                                            <div class="col-md-12">
                                                <div class="form-floating mb-3 mb-md-0">

                                                    <input type="text" class="form-control" name="golden_date"
                                                           id="golden_date"
                                                           placeholder=""
                                                           data-jdp> <label for="golden_date">تاریخ
                                                    طلایی</label>
                                                    {% if form.golden_date.errors %}
                                                        <div class="text-danger">{{ form.golden_date.errors }}</div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>

                                        <!-- فیلد قیمت -->
                                        <div class="row mb-3">
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input type="number" class="form-control" placeholder=""
                                                           name="price" id="price">
                                                    <label for="price">قیمت</label>
                                                    {% if form.price.errors %}
                                                        <div class="text-danger">{{ form.price.errors }}</div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                            <!-- فیلد تخفیف -->
                                            <div class="col-md-6">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input type="number" class="form-control" placeholder=""
                                                           name="discount"
                                                           id="discount">
                                                    <label for="discount">تخفیف</label>
                                                    {% if form.discount.errors %}
                                                        <div class="text-danger">{{ form.discount.errors }}</div>
                                                    {% endif %}
                                                </div>
                                            </div>
                                        </div>

                                        <!-- فیلد جزئیات -->
                                        <div class="row mb-3">
                                            <div class="col-md-12">
                                                <div class="form-floating mb-3 mb-md-0">
                                                    <input type="text" class="form-control" placeholder=""
                                                           id="detail"
                                                           name="detail">
                                                    <label for="detail">جزئیات</label>  {% if form.detail.errors %}
                                                    <div class="text-danger">{{ form.detail.errors }}</div>
                                                {% endif %}
                                                </div>
                                            </div>
                                        </div>
                                        <div class="row mb-3 px-2">
                                            <button type="submit" class="btn btn-primary">ثبت</button>
                                        </div>

                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
        </div>
    </div>
    <script>

        jalaliDatepicker.startWatch();
    </script>
{% endblock %}

rent/templates/rent/all-rent.html
{% extends '_base-admin.html' %}
{% load static %}
{% block body %}
    <div class="m-5">
        <table class="table table-dark table-striped text-center  ">
            <thead class="table-light">
            <tr>
                <th>قیمت ثابت</th>
                <th>تاریخ شروع</th>
                <th>تاریخ پایان</th>
                <th>بهترین دوره</th>
                <th>دوره طلایی</th>
                <th>تخفیف</th>
                <th>قیمت کل</th>
                <th>وضعیت</th>
                <th>جزئیات</th>
            </tr>
            </thead>

            <tbody>
            {% for b in bill %}
                <tr>
                    <td>{{ b.price }}</td>
                    <td>{{ b.start_date }}</td>
                    <td>{{ b.end_date }}</td>
                    <td>{{ b.best_date }}</td>
                    <td>{{ b.golden_date }}</td>
                    <td>{{ b.discount }}</td>
                    <td>{{ b.total_price }}</td>
                    {% if b.paid == False %}
                        <td>
                            <span class="badge badge text-bg-danger">پرداخت نشده</span>
                        </td>
                    {% elif b.paid == True %}
                        <td>
                            <span class="badge text-bg-success">پرداخت شده</span>
                        </td>
                    {% endif %}
                    <td><a class="btn btn-outline-light btn-sm" href="{% url 'rent:admin_rent_details' b.pk %}">مشاهده</a></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

rent/templates/rent/rent-details.html
{% extends '_base.html' %}
{% load static %}
{% block body %}
    <div class="p-5"
         style="background-image: url('../static/img/Login_bg2.jpg'); background-size: cover; height: 90.3vh">
        <div class="container">
            <div class="card bg-dark text-light ">
                <div class="card-body p-5">
                    <div class="row gy-4 gx-0">
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                تاریخ شروع قبض : {{ bill.start_date }}

                            </div>
                        </div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                تاریخ پایان قبض : {{ bill.end_date }}
                            </div>
                        </div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                قیمت : {{ bill.price }} ریال
                            </div>
                        </div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                تخفیف : %{{ bill.discount }}
                            </div>
                        </div>
                        <div class="col-md-3"></div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 py-2 border rounded">
                                پرداختی : {{ bill.total_price }} ریال
                            </div>
                        </div>
                        <div class="col-md-3"></div>
                        <div class="col-md-3"></div>
                        <div class=" col-md-6 text-center">
                            <div class=" mx-2 p-2 border rounded">
                                {% if bill.paid == False %}

                                    <span class="badge py-2  px-3 text-bg-danger">پرداخت نشده</span>
                                    <br>
                                    <br>

                                    <button class="btn btn-sm btn-primary ">پرداخت</button>

                                {% elif bill.paid == True %}
                                    <span class="badge py-2 px-3 text-bg-success">پرداخت شده</span>

                                {% endif %}
                            </div>
                            <div class="col-md-3"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

rent/templates/rent/userRent.html
{% extends '_base.html' %}
{% block body %}
    <div class="m-5">
        <table class="table table-dark table-striped text-center  ">
            <thead class="table-light">
            <tr>
                <th>قیمت ثابت</th>
                <th>تاریخ شروع</th>
                <th>تاریخ پایان</th>
                <th>بهترین دوره</th>
                <th>دوره طلایی</th>
                <th>تخفیف</th>
                <th>قیمت کل</th>
                <th>وضعیت</th>
                <th></th>
            </tr>
            </thead>

            <tbody>
            {% for b in bill %}
                <tr>
                    <td>{{ b.price }}</td>
                    <td>{{ b.start_date }}</td>
                    <td>{{ b.end_date }}</td>
                    <td>{{ b.best_date }}</td>
                    <td>{{ b.golden_date }}</td>
                    <td>{{ b.discount }}</td>
                    <td>{{ b.total_price }}</td>
                    {% if b.paid == False %}
                        <td>
                            <span class="badge badge text-bg-danger">پرداخت نشده</span>
                        </td>
                    {% elif b.paid == True %}
                        <td>
                            <span class="badge text-bg-success">پرداخت شده</span>
                        </td>
                    {% endif %}
                    <td><button class="btn btn-outline-light btn-sm" href="{% url 'rent:rent_details' b.pk %}">جزیات</button></td>

                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}