Config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('users.urls', namespace='users')),
                  path('rent/', include('rent.urls' , namespace='rent'))
               ]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rent/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
app_name = 'rent'
urlpatterns = [
    path('' , views.RentUsersView.as_view() , name='rent_users'),
    path('admin-rent' , views.RentRoomAdmin.as_view() , name='admin_rent'),
    path('admin-rent-details/<int:pk>' , views.AdminRentRoomDetails.as_view() , name='admin_rent_details'),
    path('rent-details/<int:pk>' , views.RentRoomDetails.as_view() , name='rent_details'),
    path('all-rent/<int:pk>' , views.AllRentUser.as_view() , name='all_rent')
]
 

users/urls.py
from idlelib.textview import view_file

from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('admin_page' , views.AdminPage.as_view(), name='admin_page'),
    path('user_page' , views.user_page, name='user_page'),
    path('logout' , views.LogoutUser.as_view() , name='logout_user'),
    path('register/' , views.RegisterUserPage.as_view(), name='register'),
    path('datails/<int:id>' , views.admin_details , name='admin_details')
]

templates/_base-admin.html
<!doctype html>
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet"/>
    <link href="{% static 'assets/css/styles.css'%}" rel="stylesheet"/>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/jalali-datepicker@latest/dist/css/jalali-datepicker.min.css">


    <link rel="stylesheet" href="https://unpkg.com/@majidh1/jalalidatepicker/dist/jalalidatepicker.min.css">


    <style>

        body {
            direction: rtl;
            background-image: url("{% static 'img/Login_bg.jpg' %}");
            background-size: cover;
        }
    </style>
    <title>{% block title %}

        {% endblock %}</title>
    <style>

    </style>
</head>
<body>
{% include 'navbar.html' %}
<div id="layoutSidenav">
    <div id="layoutSidenav_nav">
        {% include 'sidenav-admin.html' %}
    </div>
    <div id="layoutSidenav_content">
        <main>
            {% block body %}
            {% endblock %}

        </main>

    </div>
</div>


<script type="text/javascript" src="https://unpkg.com/@majidh1/jalalidatepicker/dist/jalalidatepicker.min.js"></script>

<script>
    jalaliDatepicker.startWatch();
</script>


<!-- اضافه کردن JS -->
<script src="https://cdn.jsdelivr.net/npm/jalali-datepicker@latest/dist/js/jalali-datepicker.min.js"></script>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="{% static 'assets/demo/chart-area-demo.js'%}"></script>
<script src="{% static 'assets/demo/chart-bar-demo.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'assets/js/datatables-simple-demo.js'%}"></script>
</body>
</html>

templates/_base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet"/>
    <link href="{% static 'assets/css/styles.css'%}" rel="stylesheet"/>
    <style>
        {% block style %}
        {% endblock %}
        body {
            direction: rtl;
            background-image: url("{% static 'img/Login_bg2.jpg' %}");
            background-size: cover;

        }


    </style>
    <title>
        {% block title %}
        {% endblock %}
    </title>

</head>
<body>
{% include 'navbar.html' %}
{% block body %}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
<script src="{% static 'assets/demo/chart-area-demo.js'%}"></script>
<script src="{% static 'assets/demo/chart-bar-demo.js'%}"></script>
<script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'assets/js/datatables-simple-demo.js'%}"></script>
</body>
</html>

templates/navbar.html
{% block body %}
{% if user.is_authenticated %}
<nav class="sb-topnav navbar di navbar-expand navbar-dark bg-dark">
    <div class="container-fluid">
        {% if user.is_staff %}
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i
                class="fas fa-bars"></i></button>
        {% endif %}

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  mb-2 mb-lg-0">
                <li class="nav-item ">
                    <a class="nav-link active">مجتمع کوهسر</a>
                </li>
                {% if user.is_staff == False %}
                <li class="nav-item ">
                    <a class="nav-link " aria-current="page" href="{% url 'users:user_page' %}">صفحه اصلی</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link " href="{% url 'rent:rent_users' %}">اجاره ها</a>
                </li>

                <li class="nav-item">
                    <form method="post" action="{% url 'users:logout_user' %}">
                        {% csrf_token %}
                        <button class=" border-0 nav-link bg-dark" type="submit">خروج</button>
                    </form>
                </li>


                {% endif %}
            </ul>

        </div>
    </div>


</nav>
{% endif %}
<script>
    window.addEventListener('DOMContentLoaded', event => {

        // Toggle the side navigation
        const sidebarToggle = document.body.querySelector('#sidebarToggle');
        if (sidebarToggle) {
            // Uncomment Below to persist sidebar toggle between refreshes
            // if (localStorage.getItem('sb|sidebar-toggle') === 'true') {
            //     document.body.classList.toggle('sb-sidenav-toggled');
            // }
            sidebarToggle.addEventListener('click', event => {
                event.preventDefault();
                document.body.classList.toggle('sb-sidenav-toggled');
                localStorage.setItem('sb|sidebar-toggle', document.body.classList.contains('sb-sidenav-toggled'));
            });
        }

    });
</script>
{% endblock %}

templates/sidenav-admin.html
<nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
    <div class="sb-sidenav-menu">

        <div class="nav">
            <a class="nav-link" href="{% url 'users:admin_page' %}">
                <div class="mt-1 sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i>&nbsp;</div>
                داشبورد
            </a>
            <!--                <div class="sb-sidenav-menu-heading">Interface</div>-->
            {% if user.is_staff %}
            <a class="nav-link" href="{% url 'users:register' %}">
                <div class=" mt-1 sb-nav-link-icon"><i class="fas fa-columns"></i>&nbsp;</div>
                ساخت کاربر
            </a>

                <a class="nav-link" href="{% url 'rent:admin_rent' %}">
                <div class=" mt-1 sb-nav-link-icon"><i class="fas fa-columns"></i>&nbsp;</div>
                تعریف قبض
            </a>
            {% endif %}

            <a class="nav-link">
                <div class="mt-1 sb-nav-link-icon"><i class="fas fa-sign-out"></i>&nbsp;</div>
                {% if user.is_authenticated %}
                <form method="post" action="{% url 'users:logout_user' %}">
                    {% csrf_token %}
                    <button class=" border-0 p-0 nav-link bg-dark" type="submit">خروج</button>
                </form>
                {% endif %}

            </a>

        </div>
    </div>

    <div class="sb-sidenav-footer">
        <div class="small">ورود به عنوان: {{ user.username }} </div>
    </div>
</nav>

<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>